export const migrations: readonly string[] = [
  "CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS oauth_clients (id TEXT PRIMARY KEY, type TEXT NOT NULL CHECK (type IN ('public', 'confidential')), name TEXT NOT NULL, secret_hash TEXT, disabled_at INTEGER, created_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS client_redirect_uris (client_id TEXT NOT NULL, redirect_uri TEXT NOT NULL, PRIMARY KEY (client_id, redirect_uri), FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE)",
  "CREATE TABLE IF NOT EXISTS client_scopes (client_id TEXT NOT NULL, scope TEXT NOT NULL, PRIMARY KEY (client_id, scope), FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE)",
  "CREATE TABLE IF NOT EXISTS client_origins (client_id TEXT NOT NULL, origin TEXT NOT NULL, PRIMARY KEY (client_id, origin), FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE)",
  "CREATE TABLE IF NOT EXISTS authorization_requests (id TEXT PRIMARY KEY, client_id TEXT NOT NULL, redirect_uri TEXT NOT NULL, scope TEXT NOT NULL, state TEXT, nonce TEXT, code_challenge TEXT NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, user_id TEXT, status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'denied')))",
  "CREATE TABLE IF NOT EXISTS authorization_codes (code_hash TEXT PRIMARY KEY, auth_request_id TEXT NOT NULL, client_id TEXT NOT NULL, redirect_uri TEXT NOT NULL, user_id TEXT NOT NULL, scope TEXT NOT NULL, nonce TEXT, expires_at INTEGER NOT NULL, consumed_at INTEGER)",
  "CREATE TABLE IF NOT EXISTS device_grants (id TEXT PRIMARY KEY, device_code_hash TEXT NOT NULL UNIQUE, user_code_hash TEXT NOT NULL UNIQUE, user_code_display TEXT NOT NULL, client_id TEXT NOT NULL, scope TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'denied', 'used')), user_id TEXT, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, interval_seconds INTEGER NOT NULL, last_poll_at INTEGER, slow_down_count INTEGER NOT NULL DEFAULT 0)",
  "CREATE TABLE IF NOT EXISTS refresh_token_families (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, client_id TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('active', 'revoked')), created_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS refresh_tokens (id TEXT PRIMARY KEY, family_id TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, user_id TEXT NOT NULL, client_id TEXT NOT NULL, scope TEXT NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER, revoked_at INTEGER, FOREIGN KEY (family_id) REFERENCES refresh_token_families(id))",
  "CREATE TABLE IF NOT EXISTS consents (user_id TEXT NOT NULL, client_id TEXT NOT NULL, scope TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY (user_id, client_id, scope))",
  "CREATE TABLE IF NOT EXISTS revoked_access_tokens (jti TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, revoked_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS audit_events (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL, data_json TEXT NOT NULL, created_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS rate_limit_counters (key TEXT PRIMARY KEY, count INTEGER NOT NULL, window_start INTEGER NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_authorization_requests_expires_at ON authorization_requests(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_authorization_codes_expires_at ON authorization_codes(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_device_grants_expires_at ON device_grants(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_revoked_access_tokens_expires_at ON revoked_access_tokens(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_rate_limit_window_start ON rate_limit_counters(window_start)",
];
