export const schemaTables = [
  "users",
  "oauth_clients",
  "client_redirect_uris",
  "client_scopes",
  "client_origins",
  "authorization_requests",
  "authorization_codes",
  "device_grants",
  "refresh_token_families",
  "refresh_tokens",
  "consents",
  "revoked_access_tokens",
  "audit_events",
  "rate_limit_counters",
  "admin_operation_submissions",
  "storage_records",
  "storage_files",
  "storage_file_orphan_repairs",
  "account_deletion_jobs",
] as const;
